[pytest]
markers =
    fase5: spec/fase5.md
    fase6: spec/fase6.md
    fase7: spec/fase7.md
    fase8: spec/fase8.md
    fase9: spec/fase9.md
    fase10: spec/fase10.md
    fase11: spec/fase11.md
    fase12: spec/fase12.md
    fase13: spec/fase13.md
    fase14: spec/fase14.md

